/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AttrForm: typeof import('./src/components/attributes/AttrForm.vue')['default']
    AttributesContainer: typeof import('./src/components/container/AttributesContainer.vue')['default']
    AudioForm: typeof import('./src/components/attributes/attrForm/AudioForm.vue')['default']
    AudioItem: typeof import('./src/components/resources/AudioItem.vue')['default']
    AudioTrack: typeof import('./src/components/track/trackItem/AudioTrack.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FontItem: typeof import('./src/components/resources/FontItem.vue')['default']
    FormItem: typeof import('./src/components/attributes/FormItem.vue')['default']
    HeaderContainer: typeof import('./src/components/container/HeaderContainer.vue')['default']
    IconList: typeof import('./src/components/track/IconList.vue')['default']
    ImageForm: typeof import('./src/components/attributes/attrForm/ImageForm.vue')['default']
    ImageTrack: typeof import('./src/components/track/trackItem/ImageTrack.vue')['default']
    MenuList: typeof import('./src/components/resources/MenuList.vue')['default']
    Player: typeof import('./src/components/player/Player.vue')['default']
    PlayerContainer: typeof import('./src/components/container/PlayerContainer.vue')['default']
    PlayerControl: typeof import('./src/components/player/PlayerControl.vue')['default']
    ResourcesContainer: typeof import('./src/components/container/ResourcesContainer.vue')['default']
    ResourcesList: typeof import('./src/components/resources/ResourcesList.vue')['default']
    ResourcesSubList: typeof import('./src/components/resources/ResourcesSubList.vue')['default']
    TextForm: typeof import('./src/components/attributes/attrForm/TextForm.vue')['default']
    TextItem: typeof import('./src/components/resources/TextItem.vue')['default']
    TextTrack: typeof import('./src/components/track/trackItem/TextTrack.vue')['default']
    TimeLine: typeof import('./src/components/track/TimeLine.vue')['default']
    TrackHeader: typeof import('./src/components/track/TrackHeader.vue')['default']
    TrackItem: typeof import('./src/components/track/TrackItem.vue')['default']
    TrackLine: typeof import('./src/components/track/TrackLine.vue')['default']
    TrackLineItem: typeof import('./src/components/track/TrackLineItem.vue')['default']
    TrackList: typeof import('./src/components/track/TrackList.vue')['default']
    TracksContainer: typeof import('./src/components/container/TracksContainer.vue')['default']
    VideoForm: typeof import('./src/components/attributes/attrForm/VideoForm.vue')['default']
    VideoFrame: typeof import('./src/components/track/trackItem/VideoFrame.vue')['default']
    VideoTrack: typeof import('./src/components/track/trackItem/VideoTrack.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
