/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Attribute: typeof import('./src/components/container/Attribute.vue')['default']
    AttributeContainer: typeof import('./src/components/container/AttributeContainer.vue')['default']
    AttributesContainer: typeof import('./src/components/container/AttributesContainer.vue')['default']
    AudioItem: typeof import('./src/components/item/AudioItem.vue')['default']
    BaseHeader: typeof import('./src/components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./src/components/layouts/BaseSide.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    Header: typeof import('./src/components/container/Header.vue')['default']
    HeaderContainer: typeof import('./src/components/container/HeaderContainer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Player: typeof import('./src/components/container/Player.vue')['default']
    PlayerContainer: typeof import('./src/components/container/PlayerContainer.vue')['default']
    ResourcesContainer: typeof import('./src/components/container/ResourcesContainer.vue')['default']
    ResourcesItem: typeof import('./src/components/item/ResourcesItem.vue')['default']
    ResourcesList: typeof import('./src/components/ResourcesList.vue')['default']
    Side: typeof import('./src/components/container/Side.vue')['default']
    SideContainer: typeof import('./src/components/container/SideContainer.vue')['default']
    Track: typeof import('./src/components/container/Track.vue')['default']
    TrackContainer: typeof import('./src/components/container/TrackContainer.vue')['default']
    TracksContainer: typeof import('./src/components/container/TracksContainer.vue')['default']
  }
}
